return {
	-- R6
	{
		Part0 = "HumanoidRootPart",
		Part1 = "Torso",
		Type = 1,
		RPart0 = "ROOT",
		RPart1 = "Torso",
	},
	{
		Part0 = "Torso",
		Part1 = "Head",
		Type = 1,
		RPart0 = "Torso",
		RPart1 = "Head",
	},
	{
		Part0 = "Torso",
		Part1 = "Left Arm",
		Type = 1,
		RPart0 = "Torso",
		RPart1 = "Left Arm",
	},
	{
		Part0 = "Torso",
		Part1 = "Right Arm",
		Type = 1,
		RPart0 = "Torso",
		RPart1 = "Right Arm",
	},
	{
		Part0 = "Torso",
		Part1 = "Left Leg",
		Type = 1,
		RPart0 = "Torso",
		RPart1 = "Left Leg",
	},
	{
		Part0 = "Torso",
		Part1 = "Right Leg",
		Type = 1,
		RPart0 = "Torso",
		RPart1 = "Right Leg",
	},
	-- R15
	{
		Part0 = "HumanoidRootPart",
		Part1 = "LowerTorso",
		Type = 2,
		RPart0 = "ROOT",
		RPart1 = "Torso",
		Offset = CFrame.new(0, 0.5, 0),
		C0 = CFrame.new(0, 0, 0),
		C1 = CFrame.new(0, 0, 0),
	},
	{
		Part0 = "UpperTorso",
		Part1 = "Head",
		Type = 2,
		RPart0 = "Torso",
		RPart1 = "Head",
		Offset = CFrame.new(0, 0, 0),
		C0 = CFrame.new(0, 1, 0),
		C1 = CFrame.new(0, -0.5, 0),
	},
	{
		Part0 = "UpperTorso",
		Part1 = "RightUpperArm",
		Type = 2,
		RPart0 = "Torso",
		RPart1 = "Right Arm",
		Offset = CFrame.new(0, 0, 0),
		C0 = CFrame.new(1, 1, 0),
		C1 = CFrame.new(-0.5, 1, 0),
	},
	{
		Part0 = "UpperTorso",
		Part1 = "LeftUpperArm",
		Type = 2,
		RPart0 = "Torso",
		RPart1 = "Left Arm",
		Offset = CFrame.new(0, 0, 0),
		C0 = CFrame.new(-1, 1, 0),
		C1 = CFrame.new(0.5, 1, 0),
	},
	{
		Part0 = "UpperTorso",
		Part1 = "RightUpperArm",
		Type = 2,
		RPart0 = "Torso",
		RPart1 = "Right Arm",
		Offset = CFrame.new(0, 0, 0),
		C0 = CFrame.new(1, 1, 0),
		C1 = CFrame.new(-0.5, 1, 0),
	},
	{
		Part0 = "UpperTorso",
		Part1 = "RightUpperArm",
		Type = 2,
		RPart0 = "Torso",
		RPart1 = "Right Arm",
		Offset = CFrame.new(0, 0, 0),
		C0 = CFrame.new(1, 1, 0),
		C1 = CFrame.new(-0.5, 1, 0),
	},
	{
		Part0 = "UpperTorso",
		Part1 = "LeftUpperLeg",
		Type = 2,
		RPart0 = "Torso",
		RPart1 = "Left Leg",
		Offset = CFrame.new(0, 0, 0),
		C0 = CFrame.new(-0.5, -1, 0),
		C1 = CFrame.new(0, 1, 0),
	},
	{
		Part0 = "UpperTorso",
		Part1 = "RightUpperLeg",
		Type = 2,
		RPart0 = "Torso",
		RPart1 = "Right Leg",
		Offset = CFrame.new(0, 0, 0),
		C0 = CFrame.new(0.5, -1, 0),
		C1 = CFrame.new(0, 1, 0),
	},
}